"""Multi-Agent Orchestrator — decomposes tasks and routes to sub-agents."""
import json, time
from dataclasses import dataclass, field
from typing import Optional

@dataclass
class AgentTask:
    task_id: str
    description: str
    assigned_agent: str
    status: str = "pending"
    result: Optional[str] = None
    duration_ms: float = 0.0

@dataclass
class WorkflowResult:
    workflow_id: str
    original_task: str
    tasks: list = field(default_factory=list)
    final_output: str = ""
    completed: bool = False
    human_checkpoint_required: bool = False
    total_duration_ms: float = 0.0

class DataAgent:
    """Handles database queries and data retrieval."""
    name = "data_agent"
    def execute(self, instruction: str) -> str:
        time.sleep(0.01)
        if "sales" in instruction.lower():
            return '{"total_revenue": 145000, "top_product": "PROD_001", "period": "Q2 2026"}'
        elif "customer" in instruction.lower():
            return '{"total_customers": 1250, "new_customers": 87, "churn_rate": 0.04}'
        return '{"data": "retrieved", "rows": 42}'

class AnalysisAgent:
    """Performs calculations, comparisons, and insight generation."""
    name = "analysis_agent"
    def execute(self, instruction: str, data: str = "") -> str:
        time.sleep(0.01)
        if "trend" in instruction.lower():
            return "Revenue trend: +12% MoM. Top 3 growth drivers: Electronics (+23%), Clothing (+15%), Food (+8%)."
        elif "underperform" in instruction.lower():
            return "Underperforming regions: North (-8%), East (-3%). Recommended action: increase marketing spend by 15%."
        return f"Analysis complete. Key finding: performance is within expected parameters."

class ReportAgent:
    """Generates structured reports and formatted output."""
    name = "report_agent"
    def execute(self, instruction: str, analysis: str = "") -> str:
        time.sleep(0.01)
        return f"""## Executive Summary

{analysis}

### Recommended Actions
1. Review underperforming regions
2. Reallocate budget to high-growth categories
3. Schedule follow-up in 30 days

*Report generated by Multi-Agent AI System*"""

class Orchestrator:
    """Decomposes tasks and routes to appropriate sub-agents with audit trail."""
    def __init__(self, confidence_threshold: float = 0.7):
        self.data_agent = DataAgent()
        self.analysis_agent = AnalysisAgent()
        self.report_agent = ReportAgent()
        self.confidence_threshold = confidence_threshold
        self.audit_log: list = []

    def run(self, task: str, workflow_id: str = None) -> WorkflowResult:
        import uuid
        wf_id = workflow_id or str(uuid.uuid4())[:8]
        start = time.time()
        result = WorkflowResult(workflow_id=wf_id, original_task=task)
        self.audit_log.append({"event": "workflow_start", "task": task, "wf_id": wf_id})

        # Step 1: Classify task and decide if human needed
        needs_human = any(kw in task.lower() for kw in
                          ["delete", "refund", "terminate", "critical", "fire"])
        if needs_human:
            result.human_checkpoint_required = True
            result.final_output = "Human review required before proceeding."
            return result

        # Step 2: Data retrieval
        data_task = AgentTask(f"{wf_id}_1", f"Retrieve data for: {task}", "data_agent")
        data_result = self.data_agent.execute(task)
        data_task.result = data_result
        data_task.status = "completed"
        result.tasks.append(data_task)
        self.audit_log.append({"event": "agent_completed", "agent": "data_agent", "result": data_result[:100]})

        # Step 3: Analysis
        analysis_task = AgentTask(f"{wf_id}_2", f"Analyse: {task}", "analysis_agent")
        analysis_result = self.analysis_agent.execute(task, data_result)
        analysis_task.result = analysis_result
        analysis_task.status = "completed"
        result.tasks.append(analysis_task)
        self.audit_log.append({"event": "agent_completed", "agent": "analysis_agent"})

        # Step 4: Report
        report_task = AgentTask(f"{wf_id}_3", "Generate report", "report_agent")
        report_result = self.report_agent.execute(task, analysis_result)
        report_task.result = report_result
        report_task.status = "completed"
        result.tasks.append(report_task)

        result.final_output = report_result
        result.completed = True
        result.total_duration_ms = round((time.time()-start)*1000, 1)
        self.audit_log.append({"event": "workflow_complete", "duration_ms": result.total_duration_ms})
        return result
